name: minimal_portfolio_webapp
description: My Portfolio App

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.1.0
  emojis: ^0.9.3
  url_launcher: ^6.0.3
  url_strategy: ^0.2.0
  expandable: ^5.0.1
  webfeed: ^0.7.0
  cached_network_image: ^3.0.0
  http: ^0.13.3
  timelines: ^0.1.0
  intl: ^0.17.0
  rive: ^0.7.22
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/emojis/
    - assets/animations/
